#!/bin/sh

userresources=$XDG_CONFIG_HOME/X11/xresources
usermodmap=$XDG_CONFIG_HOME/X11/xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xrdb -merge $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xrdb -merge "$usermodmap"
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f"] && . "$f"
    done
    unset f
fi

# keymap
setxkbmap is

# start xbindkeys
xbindkeys -f "$XDG_CONFIG_HOME"/xbindkeys/config &

# set kbd repeat rate
xset r rate 200 60

# then start i3 or dwm
exec i3
