#!/usr/bin/env bash

# this is a simple config for herbstluftwm
hc() {
    herbstclient "$@"
}

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-e quit
hc keybind $Mod-r reload
hc keybind $Mod-Shift-q close
hc keybind $Mod-Return spawn "${TERMINAL:-xterm}" # use your $TERMINAL with xterm as fallback
hc keybind $Mod-d spawn discord-canary
hc keybind $Mod-c spawn chromium
hc keybind $Mod-a spawn dmenu_run
hc keybind $Mod-z spawn flasher $HOME/school/tafla

# basic movement in tiling and floating mode
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-s         split right   0.5
hc keybind $Mod-Shift-s   split bottom  0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-s split explode 0.5

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-q remove
hc keybind $Mod-w floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle
hc keybind $Mod-Control-f pseudotile toggle

hc keybind $Mod-space\
    or , and . compare tags.focus.curframe_wcount = 2\
        . cycle_layout +1 vertical horizontal max vertical grid\
        , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
# hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# set background
hc keybind $Mod-b spawn wal -b "#181818" --backend colorz\
    -i $HOME/pics/good -n\
    -o $CONFIG/wal/after_run.sh

wal -b "#181818" --backend colorz\
    -i $(cat $XDG_CACHE_HOME/wal/wal) -n\
    -o $CONFIG/wal/after_run.sh noset -e

# theme
col0="$(xgetres color0)"
col1="$(xgetres color1)"
col2="$(xgetres color2)"
col3="$(xgetres color3)"
col4="$(xgetres color4)"
col5="$(xgetres color5)"
col6="$(xgetres color6)"
col7="$(xgetres color7)"
col7="$(xgetres color8)"

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

hc set frame_border_active_color "$col5"
hc set frame_border_normal_color "$col8"
hc set frame_bg_active_color "$col3"
hc set frame_bg_normal_color "$col0"
hc set frame_border_width 0
hc set always_show_frame off
hc set frame_bg_transparent on
hc set frame_transparent_width 0
hc set frame_active_opacity 0
hc set frame_normal_opacity 0

hc attr theme.active.color "$col5"
hc attr theme.normal.color "$col8"
hc attr theme.urgent.color "$col2"
hc attr theme.inner_width 16
hc attr theme.inner_color "$col3"
hc attr theme.border_width 1
hc attr theme.floating.border_width 1
hc attr theme.floating.outer_width 0
hc attr theme.floating.outer_color "$col0"
hc attr theme.active.inner_color "$col3"
hc attr theme.active.outer_color "$col0"
hc attr theme.background_color "$col0"

hc set window_gap 16
hc set frame_padding 0
hc set frame_gap 16
hc set snap_distance 16
hc set snap_gap 8
hc set mouse_recenter_gap 32
hc set smart_window_surroundings off
hc set smart_frame_surroundings off

# focusing
hc set raise_on_focus true
hc set hide_covered_windows true
hc set pseudotile_center_threshold 16

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule floatplacement=center # float center
# hc rule floatplacement=smart # float smart
# give focus to most common terminals
hc rule class~'(.*[Aa]lacritty.*)' pseudotile=on
hc rule class~'(.*[Zz]oom.*)' pseudotile=on tag=3
hc rule class~'(.*jetbrains-idea.*)' pseudotile=on tag=3 focus=on
hc rule title='killme' floating=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '*│ ├└──┐'

# force autorandr screencheck
autorandr -c --force

# start polybar
$CONFIG/polybar/start.sh herbstluft

# startup script
$CONFIG/scripts/startup.sh herbstluft

# set padding
hc pad 0 42 0 42 0

# unlock, just to be sure
hc unlock

